services:
  #üóÑÔ∏è Service postgresql Database
  db:
    image: postgres:14.19-alpine3.21
    container_name: nextjs_shadcn_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextjs_shadcn_db
      POSTGRES_USER: nextjs_shadcn_db_user
      POSTGRES_PASSWORD: password_user
    ports:
      - "5432:5432"
    volumes:
      - nextjs_shadcn_db:/var/lib/postgresql/data

volumes:
  nextjs_shadcn_db:
